---

spring:
  cloud:
    config:
      server:
        git:
          uri: ${vcap.services.config-service.credentials.uri}
          
security:
  user:
    name: ${vcap.services.config-basic-auth.credentials.username:cconfig}
    password: ${vcap.services.config-basic-auth.credentials.password:cpassword}