---

info:
  description: Training configuration repo

---  
spring:
  profiles: cloud
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://ceureka:cpassword@http://eureka-dr-restless-gnu.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.eureka-dr.uris}
    nonSecurePort: 80 