---

info:
  description: Training configuration repo

---  
spring:
  profiles: cloud
  
  eureka.instance.hostname: ${vcap.application.eureka-dr.uris}
  eureka.instance.nonSecurePort: 80
  
  eureka:
    client:
      serviceUrl:
        defaultZone: http://ceureka:cpassword@http://eureka-dr-restless-gnu.cfapps.io/eureka