---

info:
  description: Training configuration repo

---  
spring:
  profiles: cloud
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://ceureka:cpassword@eureka-dr-restless-gnu.cfapps.io/eureka
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80 
